title: Morgane Maurel Montage
baseurl: /
permalink: '/:title/'
collections:
  posts:
    permalink: '/posts/:title/'
description: Morgane Maurel Montage
color_scheme: light
accent_color: yellow
header:
  title: Morgane Maurel
  has_nav: true
  nav_links:
    # - label: Home
    #   url: /
    #   style: link
    - label: Films
      url: /portfolio/
      style: button
    # - label: Blog
    #   url: /blog/
    #   style: link
    - label: About
      url: /about/
      style: link
    - label: Contact
      url: /contact/
      style: link
footer:
  content: >-
    &copy; Morgane Maurel 2021. All rights reserved.
  has_social: true
  social_links:
    # - label: Twitter
    #   url: 'https://twitter.com/'
    #   style: icon
    #   icon_class: fa-twitter
    #   new_window: true
    # - label: Dribbble
    #   url: 'https://dribbble.com/'
    #   style: icon
    #   icon_class: fa-dribbble
    #   new_window: true
    - label: Facebook
      url: 'https://www.facebook.com/profile.php?id=100012547476174'
      style: icon
      icon_class: fa-facebook
      new_window: true
    - label: LinkedIn
      url: 'https://www.linkedin.com/in/morganemaurel'
      style: icon
      icon_class: fa-linkedin
      new_window: true
sass:
  indentWidth: 4
  style: nested
  precision: 10
plugins:
  - jekyll-menus
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - README.md
  - netlify.toml
  - stackbit-build.sh
  - stackbit-pull.js
